-- MySQL Script generated by MySQL Workbench
-- Mon May 30 14:10:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema isbaza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema isbaza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `isbaza` DEFAULT CHARACTER SET utf8 ;
USE `isbaza` ;

-- -----------------------------------------------------
-- Table `isbaza`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isbaza`.`customer` (
  `ID` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Phone` VARCHAR(45) NULL DEFAULT NULL,
  `Carmodel` VARCHAR(45) NULL DEFAULT NULL,
  `Carplate` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `isbaza`.`custserv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isbaza`.`custserv` (
  `ID` INT(11) NOT NULL,
  `FKcustomer` INT(11) NULL DEFAULT NULL,
  `FKservice` INT(11) NULL DEFAULT NULL,
  `FullPrice` INT(11) NULL DEFAULT NULL,
  `Fixed` VARCHAR(45) NULL DEFAULT NULL,
  `Paid` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `isbaza`.`id_gen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isbaza`.`id_gen` (
  `gen_name` VARCHAR(45) NOT NULL,
  `gen_val` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`gen_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `isbaza`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isbaza`.`service` (
  `ID` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Price` INT(11) NULL DEFAULT NULL,
  `Parts` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
